### ISSUE TITLE
FTC SDK 4.x support

### ISSUE THREAD

**Issue by rbrott** [OpenFTC/RevExtensions2#3]
Using RE2 with FTC SDK 4.x leads to errors like the following:
```
Process: com.qualcomm.ftcrobotcontroller, PID: 18716
    java.lang.NoSuchMethodError: No interface method getMotorType()Lcom/qualcomm/robotcore/hardware/configuration/MotorConfigurationType; in class Lcom/qualcomm/robotcore/hardware/DcMotor; or its super classes (declaration of 'com.qualcomm.robotcore.hardware.DcMotor' appears in /data/app/com.qualcomm.ftcrobotcontroller-2/base.apk:classes2.dex)
        at org.openftc.revextensions2.ExpansionHubMotor.<init>(ExpansionHubMotor.java:42)
        at org.openftc.revextensions2.Utils.hotswapHardwareMap(Utils.java:89)
        at org.openftc.revextensions2.RevExtensions2.init(RevExtensions2.java:42)
```
Closer inspection suggests that there are a number of breaking API changes in 4.x that affect RE2.

**Comment by ItsHarper** [comment]
Weird error. `DcMotor.getMotorType()` is definitely still a method in 4.0.

That being said, there were internal changes related to configuration that I made in 4.0, so I could have broken something, especially since the line between "public API" and "internal API" is extremely blurry right now. We do our best not to break anything for teams. RevExtensions is clearly a special case here.

**Comment by ItsHarper** [comment]
@FROGbots-4634 Maybe you need to update the aars that you compile against. Are they from 3.x?

**Comment by rbrott** [comment]
Yes `DcMotor.getMotorType()` still exists but `MotorConfigurationType` changed packages. I also think the current AARs are still from 3.x (hence why they compile).

**Comment by Windwoes** [comment]
@NoahAndrews yes the AARs are from 3.x.

Hmm... I'll look into this when I have time.

**Comment by ItsHarper** [comment]
Ooh true. Yeah, I didn't realize that was exposed through an explicitly user facing API. 

This should be an easy fix at least. Just switch the AARs and do whatever you need to from there.

**Comment by Windwoes** [comment]
Hmmm yeah. Shoot, now we won't be backwards compatible anymore :(

**Comment by Windwoes** [comment]
@rbrott ok, theoretically fixed in [this](https://github.com/OpenFTC/RevExtensions2/commit/2cd4dbdb18e9616649152a14c6eda296793aead9) commit.

**Comment by Windwoes** [comment]
RE2 v1.1 has been released, supporting SDK v4.x
