### ISSUE TITLE
How to change the type of expansion hub

### ISSUE THREAD

**Issue by Teagan-Brohman** [OpenFTC/RevExtensions2#4]
Hello, I am just starting out with this repository and am getting an error about being unable to find our hardware device even though it is named properly on both the phone and the config. Since this is the case I assumed it was the type of expansion hub which is calls for the ExpansionHubEx type. Is this a thing specific for the phone or is it done physically in the code. Any help would be appreciate. Thanks!

**Comment by Windwoes** [comment]
So are you saying you're getting something like this?

```
EventLoopManager: Event loop threw an exception
EventLoopManager: java.lang.IllegalArgumentException: Unable to find a hardware device with name "Expansion Hub 2" and type ExpansionHubEx
EventLoopManager:     at com.qualcomm.robotcore.hardware.HardwareMap.get(HardwareMap.java:174)
```

I just tested the latest version of the library myself was unable to replicate the issue. Make sure you're passing in the correct name here:

```expansionHub = hardwareMap.get(ExpansionHubEx.class, "NAME IN CONFIG FILE");```

**Comment by Teagan-Brohman** [comment]
Yeah that was the error I was getting. I managed to get around this issue by placing the code that points towards the hub in our tele-op and not in the hardware map. Thanks for the help!
